### ISSUE TITLE
Failed to get replSetGetConfig: IntDecodeValue can only truncate float64 to an integer type when truncation is enabled.

### ISSUE THREAD

**Issue by ckailantzis** [bitnami/bitnami-docker-mongodb-exporter#4]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

Hi there, 

using image version 0.11.2 on kubernetes, and try to connect to one mongoDB cluster the following error is thrown.
`Failed to get replSetGetConfig: IntDecodeValue can only truncate float64 to an integer type when truncation is enabled.`

Connecting with mongo shell and running a rs.conf() command, shows that one of the shards has unfortunately priority: 6.5 set. Could you please provide a fix for this ? 

Similar issue can be checked also on Percona's side: https://jira.percona.com/browse/PMM-6113?attachmentSortBy=dateTime. Apparently there was a patch provided from their end. Also PR tracked here: https://github.com/percona/mongodb_exporter/pull/213

Thanks in advance,.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
using bitnami/mongodb-exporter:0.11.2 on Kubernetes
```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by FraPazGal** [comment]
Hi @ckailantzis,

Thank you for opening this issue! We obtain the source code of this image from upstream, directly from [Percona](https://github.com/percona/mongodb_exporter). Using our CI/CD tools, once there is patch released in upstream we update our image with the new version. As this is an issue related to the source code with a PR about to be merged, there shouldn't take too long for this issue to also be solved in our container.

**Comment by WuWhite** [comment]
Your user group permissions are insufficient and you need to add clusterAdmin permissions

**Comment by Mauraza** [comment]
Hi @WuWhite,

Could you explain a little more about the sufficient permission?
