### ISSUE TITLE
[Question] metric data doesn't include "pod-name"

### ISSUE THREAD

**Issue by tom1005** [bitnami/bitnami-docker-mongodb-exporter#5]
Hi.

I'm using "mongodb-exporter" in k8s.
But metric data doesn't include pod-name.
Can I see "pod-name" in all metric of mongodb?

metric of mongodb information in prometheus
mongodb_network_bytes_total{app="mongodb",app_kubernetes_io_component="metrics",app_kubernetes_io_instance="backup-test-repksh3",app_kubernetes_io_managed_by="Tiller",app_kubernetes_io_name="mongodb",helm_sh_chart="mongodb-8.3.2",instance="172.30.85.191:9216",job="kubernetes-service-endpoints",namespace="backup-test",release="backup-test-repksh3",service="backup-test-repksh3-mongodb-metrics",state="in_bytes"}

**Comment by andresbono** [comment]
Hi @tom1005, I'd say your question is related to the Prometheus configuration, not the `bitnami/mongodb-exporter` container, right?

You may want to use the [community channels](https://prometheus.io/community/) for that.

**Comment by tom1005** [comment]
@andresbono Thanks for reply.

I'll check your point.

If I have additional question, I will come back here :)

Best regard.

**Comment by andresbono** [comment]
Thanks, @tom1005!!
