### ISSUE TITLE
docker-compser - replice set - error>a direct connection cannot be made if multiple hosts are specified

### ISSUE THREAD

**Issue by AlexDag** [bitnami/bitnami-docker-mongodb-exporter#7]
**Description**

putting into docker-compse.yml URI with multiply hosts of Replica Set - shows the error>a direct connection cannot be made if multiple hosts are specified
**Steps to reproduce the issue:**

1. [First Step]
vi docker-compose.yml 
 - MONGODB_URI=mongodb://mongodb_exporter:ppppppsswd@mongo1:27017,mongo2:27017,mongo3:27017/?authSource=admin
2. [Second Step]
docker-compose up  -d
3. [and so on...]
http://mymongoexporterhost:9216/metrics

**Describe the results you received:**
time="2020-12-09T20:32:25Z" level=error msg="Cannot connect to MongoDB: a direct connection cannot be made if multiple hosts are specified"

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by AlexDag** [comment]
MongoDB shell version v4.4.2

**Comment by juan131** [comment]
Hi @AlexDag 

That's very likely to be related with the exporter appending `?connect=direct` after `MONGODB_URI`.

Could you try passing the `--mongodb.uri` flag to the exporter instead of using the **MONGODB_URI** environment variable? I mean, sth like:

```
./mongodb_exporter --mongodb.uri=admin:admin123456@mongo1:27017,mongo2:27017,mongo3:27017/admin/
```

**Comment by AlexDag** [comment]
Hi Juan Ariza,
I've run mongodb_exporter directly inside docker container of bitnami image:
I used the another port for metris: 9217
fbcec47ba8eb:*/opt/bitnami/mongodb-exporter/bin*$ *./mongodb_exporter
*--web.listen-address=":9217"
--mongodb.uri=mongodb://mongodb_exporter:pppssswd@vsmart-mdb01
:27017,vsmart-mdb02:27017,vsmart-mdb03:27017/admin
INFO[0000] Starting HTTP server for http://:9217/metrics ...
 source="server.go:144"
ERRO[0022] Cannot connect to MongoDB: a direct connection cannot be made if
multiple hosts are specified

thanks for your support.
Alex

**Comment by juan131** [comment]
Hi @AlexDag 

I checked how we configure the exporter in our MongoDB chart when setting up a replicaset (see https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/statefulset.yaml) and it seems we're using one exporter per MongoDB replicas.

The scenario is sth like this:

```
            ┌───────────┐            ┌───────────┐            ┌───────────┐
            |  exporter |            |  exporter |            |  exporter |
      ┌───────────┐     |      ┌───────────┐     |       ┌───────────┐    |
      │ MongoDB 0 │─────┘      │ MongoDB 1 │─────┘      │ MongoDB N │─────┘       
      │  Server   │            │  Server   │    ....    │  Server   |
      │   Pod     │            │   Pod     │            │   Pod     │
      └───────────┘            └───────────┘            └───────────┘
             primary           secondary          secondary
```

Then we configure Prometheus to scrap metrics from each exporter.

**Comment by AlexDag** [comment]
Hi @juan131 ,
thank for details.
