### ISSUE TITLE
Percona MongoDB Overview Grafana Dashboard don´t work with this mongodb exporter

### ISSUE THREAD

**Issue by fjmatos** [bitnami/bitnami-docker-mongodb-exporter#9]
**Description**

Hi bitname:  

I´ve been testing this container to get data of mongo on a grafana server.

I have deployed :   `bitnami/mongodb-exporter:latest`   using a docker-compose.yml file.

I can see the metrics in the port  9216.

The metrics are like this:

````
# HELP mongodb_ss_uptime serverStatus.
# TYPE mongodb_ss_uptime untyped
mongodb_ss_uptime{cl_id="",cl_role="mongod",rs_state="0"} 1.042293e+06
# HELP mongodb_ss_uptimeEstimate serverStatus.
# TYPE mongodb_ss_uptimeEstimate untyped
mongodb_ss_uptimeEstimate{cl_id="",cl_role="mongod",rs_state="0"} 1.042293e+06
# HELP mongodb_ss_uptimeMillis serverStatus.
# TYPE mongodb_ss_uptimeMillis untyped
mongodb_ss_uptimeMillis{cl_id="",cl_role="mongod",rs_state="0"} 1.042293873e+09
```` 

And I can see that all metrics field, are all like this :   mongodb_ss_......

I got a grafana server, and I´ve deployed the :  MongoDB Overview of Percona  (id: 2538) 

I can see data in Prometheus , but mongodb grafana dashboards PromQL queries are of this type:

```
mongodb_mongod_connections{instance=~"$host", state="current"} or
mongodb_mongos_connections{instance=~"$host", state="current"}
````

all queries are using  :  mongodb_mongod_.......  or mongodb_mongos_......

So nothing appear in the grafana panel.

I don´t understand why the metrics are different :  you are using mongodb_ss_...... and Percona is using mongodb_mongod_.... or mongodb_mongos_......   ,  if you are using the Percona's exporter

- versions:

```
docker version:  20.10.3, build 48d30b5
docker compose version: 1.25.5-rc1, build 4afe60f2
mongodb:    mongo:latest
mongodb-exporter:    bitnami/mongodb-exporter:latest
prometheus:  prom/prometheus:latest
grafana: 7.3.1
grafana dashboard: ID 2583
```

Best regards.

**Comment by juan131** [comment]
HI @fjmatos 

It's very likely that you need to stick `0.11.x` series of the exporter for the metrics to be compatible with that dashboard, find more information in this issue:

- https://github.com/bitnami/bitnami-docker-mongodb-exporter/issues/8

Another alternative shared by @jonhatallasf consists on adding the `--compatible-mode` flag to the exporter.

**Comment by fjmatos** [comment]
Really thank you for your help , @juan131 

Changing from  latest  to 0.11.2 ,  y got metric field that are recognized by the Percona grafana Mongodb Overview Dashboard.
(only some queries are not correct, but only two).

I close the issue as solved.

**Comment by juan131** [comment]
Great!! I'm glad you could solve it.
